name: dbt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-duckdb

      - name: Run dbt deps
        run: dbt deps

      - name: Run dbt compile
        run: dbt compile

      - name: Run dbt run
        run: dbt run

      - name: Run dbt test
        run: dbt test
