version: 2

models:
  - name: model_mart_driver_incentive_impact
    description: "Impact of incentive programs on driver performance"
    columns:
      - name: driver_id
        tests:
          - not_null
      - name: incentive_program
        tests:
          - not_null

  - name: model_mart_driver_performance
    description: "Overall performance metrics for each driver"
    columns:
      - name: driver_id
        tests:
          - not_null
      - name: total_order
        tests:
          - not_null

  - name: model_mart_driver_zone_heatmap
    description: "Heatmap of delivery activity and failed requests by zone"
    columns:
      - name: delivery_zone
        tests:
          - not_null


  - name: model_mart_campaign_performance
    description: "Campaign performance with attribution to orders and revenue"
    columns:
      - name: campaign_id
        tests:
          - not_null
      - name: total_revenue
        tests:
          - not_null

  - name: model_mart_customer_acquisition
    description: "New customer acquisition from campaign efforts"
    columns:
      - name: campaign_id
        tests:
          - not_null
      - name: acquisition_date
        tests:
          - not_null

  - name: model_mart_retargeting_performance
    description: "Performance of retargeting campaigns"
    columns:
      - name: campaign_id
        tests:
          - not_null
      - name: total_ad_cost
        tests:
          - not_null

  - name: model_mart_complaint_summary
    description: "Summary of all complaints"
    columns:
      - name: issue_type
        tests:
          - not_null
      - name: complaint_date
        tests:
          - not_null
      - name: total_complaints
        tests:
          - not_null

  - name: model_mart_driver_related_complaints
    description: "Complaints associated with drivers"
    columns:
      - name: driver_id
        tests:
          - not_null
      - name: total_orders
        tests:
          - not_null

  - name: model_mart_restaurant_quality_complaint
    description: "Complaints about restaurant quality"
    columns:
      - name: restaurant_id
        tests:
          - not_null
      - name: total_orders
        tests:
          - not_null
